# # define pipeline name
# name: Deploy To Server

# # define trigger
# on:
#   push:
#     branches: 
#       - main

# # define the body/workflows
# jobs:
#   deploy-to-server:
#     name: Deploy To Server
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Run Command 1
#       run: ls -l

#     - name: Run Command 2
#       run: |
#         hostnamectl
#         sudo -l



name: Deploy VPC to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-vpc:
    name: Deploy VPC
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1  # Change to your region

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform config
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
    - name: Destroy Terraform
      run: terraform apply --auto-approve
