# # define pipeline name
# name: Deploy To Server

# # define trigger
# on:
#   push:
#     branches: 
#       - main

# # define the body/workflows
# jobs:
#   deploy-to-server:
#     name: Deploy To Server
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Run Command 1
#       run: ls -l

#     - name: Run Command 2
#       run: |
#         hostnamectl
#         sudo -l



# name: Deploy VPC to AWS

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   deploy-vpc:
#     name: Deploy VPC
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v3

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: eu-north-1  # Change to your region

#     - name: Initialize Terraform
#       run: terraform init

    # - name: Validate Terraform config
    #   run: terraform validate

    # - name: Plan Terraform
    #   run: terraform plan -out=tfplan

    # - name: Apply Terraform
    #   run: terraform apply -auto-approve tfplan
    # - name: Destroy Terraform
    #   run: terraform destroy --auto-approve



name: Import-Move-to-S3-Destroy-VPCs-on-Push

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  destroy-vpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create Terraform config
      run: |
        cat <<EOF > main.tf
        provider "aws" {
          region = "${{ secrets.AWS_REGION }}"
        }

        resource "aws_vpc" "vpc1" {}
        resource "aws_vpc" "vpc2" {}

        terraform {
          backend "s3" {
            bucket         = "samude-bucket00001"
            key            = "vpc/terraform.tfstate"
            region         = "${{ secrets.AWS_REGION }}"
            
          }
        }
        EOF

    - name: Init without backend
      run: terraform init -backend=false

    - name: Import VPCs
      run: |
        terraform import aws_vpc.vpc1 ${{ secrets.VPC1_ID }}
        terraform import aws_vpc.vpc2 ${{ secrets.VPC2_ID }}

    - name: Migrate to S3 backend
      run: terraform init -migrate-state

    - name: Destroy VPCs
      run: terraform destroy -auto-approve

